Update to v0.3.6
kyma-incubator/sap-btp-service-operator pull request #25
Opened 2023-01-20 13:33 UTC by ukff

Update to v0.3.6

2023-01-20 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/sap-btp-service-operator?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/sap-btp-service-operator?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/sap-btp-service-operator?pullRequest=25) it.</sub>

2023-01-20 15:38 UTC, PK85 requested changes

2023-01-20 15:38 UTC, PK85 commented on chart/values.yaml
> +    enabled: false
we need "true"

2023-01-20 15:38 UTC, PK85 commented on chart/values.yaml
> +    certManager: true
we need "false" We will use selfsigned certs.

2023-01-20 15:38 UTC, PK85 commented on chart/values.yaml
> +  rbacProxy:
this is ok, looks they make it configurable.

2023-01-20 15:38 UTC, PK85 commented on chart/values.yaml
> +  req_cpu_limit: 100m
keep it 10m

2023-01-20 15:38 UTC, PK85 commented on chart/values.yaml
> +  enable_leader_election: true
does enable_leader_election to true is related to replica_count 2?

2023-01-20 15:38 UTC, PK85 commented on chart/templates/webhook.yml
> -{{- if .Values.manager.certificates.selfSigned }}
we need that configuration back. @piotrmiskiewicz without that current solution will not work right?

2023-01-20 15:46 UTC, PK85 commented on chart/templates/webhook.yml
> -{{- if .Values.manager.certificates.selfSigned }}
Btw from where u got that 0.3.6 webhook.yml? Upstream 0.3.6 webhook yaml: https://github.com/SAP/sap-btp-service-operator/blob/v0.3.6/sapbtp-operator-charts/templates/webhook.yml

2023-01-23 10:20 UTC, wozniakjan commented on chart/values.yaml
> +  enable_leader_election: true
correct, leader election started in replicated HA control-plane and got adopted by controller-runtime (and kubebuilder)
https://github.com/kubernetes-sigs/controller-runtime/blob/35b47fcad8585d12e7a4a4dd66add945a1c86a7a/pkg/leaderelection/doc.go#L18-L22

2023-01-23 11:22 UTC, wozniakjan commented on chart/templates/deployment.yml
> -        sidecar.istio.io/inject: "false"
nit: I think we should keep the istio disablement annotation. If users click on installing istio in kyma, btp-operator will stop working which is imho bad UX.

but after upstream merged https://github.com/SAP/sap-btp-service-operator/pull/214#discussion_r1039550062, we can put it to `values.yaml` as recommended below

2023-01-23 11:22 UTC, wozniakjan commented on chart/values.yaml
>  manager:
continuing the nit with proposed improvement:
```suggestion
manager:
  annotations:
    sidecar.istio.io/inject: "false"
```

2023-01-23 11:22 UTC, wozniakjan commented on chart/values.yaml
> +    req_cpu_limit: ""
we should either omit these or set them to some correct values as this renders to invalid resources containing under `deployment.spec.template.spec.containers[kube-rbac-proxy]`
```
...
          resources:
            limits:
            requests:
...
```

2023-01-23 12:55 UTC, PK85 commented on chart/values.yaml
> +    req_cpu_limit: ""
Lets omit them, as before we had default values for kube-rbac-proxy

2023-01-24 11:16 UTC, wozniakjan approved these changes
/lgtm
/approve

2023-01-24 13:46 UTC, merged